# POST /api/v1/orders - Create New Order
# Complete OpenAPI specification example for Week 4

openapi: 3.1.0
info:
  title: Order Management API - Create Order Endpoint
  version: 1.0.0
  description: Example specification for the Create Order endpoint

paths:
  /api/v1/orders:
    post:
      operationId: createOrder
      summary: Create a new order
      description: |
        Create a new order for the authenticated customer.
        The order will be created with status "Pending".
        
        **Business Rules:**
        - Customer must exist and be active
        - All items must exist and be in stock
        - Order must have 1-100 items
        - Each item quantity must be 1-99
        - Total is automatically calculated from items
      tags:
        - Orders
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: Order creation request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
            examples:
              singleItem:
                summary: Order with single item
                value:
                  customerId: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                  items:
                    - itemId: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                      quantity: 2
              multipleItems:
                summary: Order with multiple items
                value:
                  customerId: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                  items:
                    - itemId: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                      quantity: 2
                    - itemId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                      quantity: 1
                    - itemId: "b2c3d4e5-f6a7-8901-bcde-f12345678901"
                      quantity: 3
      responses:
        '201':
          description: Order created successfully
          headers:
            Location:
              description: URL of the created order
              schema:
                type: string
                format: uri
              example: "/api/v1/orders/550e8400-e29b-41d4-a716-446655440000"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                customerId: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
                items:
                  - itemId: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                    itemName: "Widget Pro"
                    quantity: 2
                    unitPrice: 29.99
                    subtotal: 59.98
                  - itemId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
                    itemName: "Gadget Basic"
                    quantity: 1
                    unitPrice: 15.00
                    subtotal: 15.00
                status: "Pending"
                total: 74.98
                createdAt: "2026-01-20T10:30:00Z"
                updatedAt: "2026-01-20T10:30:00Z"
                cancelledAt: null
                cancellationReason: null
        '400':
          description: Invalid request body
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
              examples:
                missingFields:
                  summary: Missing required fields
                  value:
                    type: "https://api.example.com/errors/validation-error"
                    title: "Validation Error"
                    status: 400
                    detail: "Request validation failed"
                    instance: "/api/v1/orders"
                    traceId: "abc123def456"
                    violations:
                      - field: "customerId"
                        message: "must not be null"
                      - field: "items"
                        message: "must not be empty"
                invalidQuantity:
                  summary: Invalid item quantity
                  value:
                    type: "https://api.example.com/errors/validation-error"
                    title: "Validation Error"
                    status: 400
                    detail: "Request validation failed"
                    instance: "/api/v1/orders"
                    traceId: "def456ghi789"
                    violations:
                      - field: "items[0].quantity"
                        message: "must be between 1 and 99"
                tooManyItems:
                  summary: Too many items
                  value:
                    type: "https://api.example.com/errors/validation-error"
                    title: "Validation Error"
                    status: 400
                    detail: "Request validation failed"
                    instance: "/api/v1/orders"
                    traceId: "ghi789jkl012"
                    violations:
                      - field: "items"
                        message: "must have at most 100 items"
        '401':
          description: Authentication required
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
              example:
                type: "https://api.example.com/errors/unauthorized"
                title: "Unauthorized"
                status: 401
                detail: "Authentication token is missing or invalid"
                instance: "/api/v1/orders"
        '404':
          description: Customer or item not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
              examples:
                customerNotFound:
                  summary: Customer does not exist
                  value:
                    type: "https://api.example.com/errors/not-found"
                    title: "Not Found"
                    status: 404
                    detail: "Customer 7c9e6679-7425-40de-944b-e07fc1f90ae7 not found"
                    instance: "/api/v1/orders"
                    traceId: "mno345pqr678"
                itemNotFound:
                  summary: Item does not exist
                  value:
                    type: "https://api.example.com/errors/not-found"
                    title: "Not Found"
                    status: 404
                    detail: "Item f47ac10b-58cc-4372-a567-0e02b2c3d479 not found"
                    instance: "/api/v1/orders"
                    traceId: "stu901vwx234"
        '409':
          description: Business rule conflict
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
              examples:
                outOfStock:
                  summary: Item out of stock
                  value:
                    type: "https://api.example.com/errors/out-of-stock"
                    title: "Item Out of Stock"
                    status: 409
                    detail: "Item 'Widget Pro' is currently out of stock"
                    instance: "/api/v1/orders"
                    traceId: "yza567bcd890"
                    itemId: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                    availableQuantity: 0
                insufficientStock:
                  summary: Insufficient stock
                  value:
                    type: "https://api.example.com/errors/insufficient-stock"
                    title: "Insufficient Stock"
                    status: 409
                    detail: "Only 5 units of 'Widget Pro' available, requested 10"
                    instance: "/api/v1/orders"
                    traceId: "efg123hij456"
                    itemId: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                    requestedQuantity: 10
                    availableQuantity: 5
                customerInactive:
                  summary: Customer account inactive
                  value:
                    type: "https://api.example.com/errors/customer-inactive"
                    title: "Customer Inactive"
                    status: 409
                    detail: "Customer account is not active"
                    instance: "/api/v1/orders"
                    traceId: "klm789nop012"
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
              example:
                type: "https://api.example.com/errors/internal-error"
                title: "Internal Server Error"
                status: 500
                detail: "An unexpected error occurred. Please try again later."
                instance: "/api/v1/orders"
                traceId: "qrs345tuv678"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CreateOrderRequest:
      type: object
      description: Request body for creating a new order
      required:
        - customerId
        - items
      properties:
        customerId:
          type: string
          format: uuid
          description: ID of the customer placing the order
          example: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        items:
          type: array
          description: Line items to include in the order
          minItems: 1
          maxItems: 100
          items:
            $ref: '#/components/schemas/CreateOrderItemRequest'

    CreateOrderItemRequest:
      type: object
      description: A line item in the order creation request
      required:
        - itemId
        - quantity
      properties:
        itemId:
          type: string
          format: uuid
          description: ID of the item to order
          example: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
        quantity:
          type: integer
          minimum: 1
          maximum: 99
          description: Number of units to order
          example: 2

    Order:
      type: object
      description: A complete order with all details
      required:
        - id
        - customerId
        - items
        - status
        - total
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique order identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        customerId:
          type: string
          format: uuid
          description: Customer who placed the order
          example: "7c9e6679-7425-40de-944b-e07fc1f90ae7"
        items:
          type: array
          description: Line items in the order
          minItems: 1
          maxItems: 100
          items:
            $ref: '#/components/schemas/OrderItem'
        status:
          $ref: '#/components/schemas/OrderStatus'
        total:
          type: number
          format: decimal
          minimum: 0
          description: Calculated total of all items
          example: 74.98
        createdAt:
          type: string
          format: date-time
          description: When the order was created
          readOnly: true
          example: "2026-01-20T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          description: When the order was last modified
          readOnly: true
          example: "2026-01-20T10:30:00Z"
        cancelledAt:
          type: string
          format: date-time
          nullable: true
          description: When the order was cancelled (if applicable)
          example: null
        cancellationReason:
          type: string
          maxLength: 500
          nullable: true
          description: Reason for cancellation (if applicable)
          example: null

    OrderItem:
      type: object
      description: A line item in an order
      required:
        - itemId
        - itemName
        - quantity
        - unitPrice
        - subtotal
      properties:
        itemId:
          type: string
          format: uuid
          description: Reference to the catalog item
          example: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
        itemName:
          type: string
          description: Name of the item at time of order
          example: "Widget Pro"
        quantity:
          type: integer
          minimum: 1
          maximum: 99
          description: Number of units ordered
          example: 2
        unitPrice:
          type: number
          format: decimal
          minimum: 0
          description: Price per unit at time of order
          example: 29.99
        subtotal:
          type: number
          format: decimal
          minimum: 0
          description: Calculated subtotal (quantity × unitPrice)
          readOnly: true
          example: 59.98

    OrderStatus:
      type: string
      enum:
        - Pending
        - Confirmed
        - Shipped
        - Delivered
        - Cancelled
      description: Current lifecycle status of an order
      example: Pending

    ProblemDetail:
      type: object
      description: RFC 7807 Problem Details for HTTP APIs
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          description: URI reference identifying the problem type
        title:
          type: string
          description: Short, human-readable summary
        status:
          type: integer
          description: HTTP status code
        detail:
          type: string
          description: Human-readable explanation
        instance:
          type: string
          description: URI reference for this occurrence
        traceId:
          type: string
          description: Correlation ID for debugging
        violations:
          type: array
          items:
            $ref: '#/components/schemas/Violation'

    Violation:
      type: object
      required:
        - field
        - message
      properties:
        field:
          type: string
        message:
          type: string
